services:
  postgres:
    container_name: postgres
    image: postgres
    env_file: .env
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    container_name: api
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: on-failure
    volumes:
      - ./app:/code/app
    ports:
      - 8000:8000

volumes:
  postgres-data:
